version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: notes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=32apj*c483c%hc5&cs1hejx52fz3(4jg8*18v38iepgsh^nyc4
      - DATABASE_URL=postgres://myuser:1234@db/notes_db
    depends_on:
      - db

volumes:
  postgres_data: